name: classpractice
description: practice project to teach student

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  font_awesome_flutter: ^9.2.0
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/

# example:
  fonts:
    - family: Roboto Mono
      fonts:
        - asset: assets/fonts/RobotoMono-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf
          style: italic
    - family: Dancing Script
      fonts:
        - asset: assets/fonts/DancingScript-VariableFont_wght.ttf
