name: classpractice
description: practice project to teach student

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:
#  assets:
#    - images/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - assets: fonts/Schyler-Regular.ttf
  #       - assets: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - assets: fonts/TrajanPro.ttf
  #       - assets: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

